apiVersion: v1
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: 0chan-default-sc
provisioner: disk-csi-driver.mks.ycloud.io
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: network-ssd
  csi.storage.k8s.io/fstype: ext4
allowVolumeExpansion: true
reclaimPolicy: Retain
